### ISSUE TITLE
Python in memory script load question

### ISSUE THREAD

**Issue by S3cur3Th1sSh1t** [alxchk/pupy#32]
Hey,

im currently trying to find ways for reflective loading of python compiled binaries to memory on a windows host but till now i was not able to successfully get this working. Pupy does exactly this for example with lazagne.py. I browsed the code to find the technique for it but could not find it so far. So could you tell me how pupy loads and executes the python code in memory? Is the python interpreter embedded in the pupy agent/client?

#### What i tried so far:

1. Use Invoke-ReflectivePEInjection (Powershell) / PEloader of Subtee (C#) to load the bytes of an pyinstaller compiled python exe in memory - im pretty sure this is not working because only C/C++ Compiled Binaries can be loaded by theese scripts because of the binary structure.

2. Convert the Python Code to an CPython Executable using Nuitka. The python code is then embedded in C-Code which is compiled to an binary. The compiled binary works pretty well and is a C-Binary but this one is still not reflectively loadable by Invoke-ReflectivePEInjection / C# PEloader. The needed DLL files are located and loaded successfully but the binary itself is not executed in memory. There are no error messages which makes debugging harder. For Invoke-ReflectivePEInjection the whole Powershell process is killed after loading the executable - most likely a crash.

3. Convert the Nuitka created CPython Executable to Shellcode via donut or PE2Shellcode and try to load the shellcode in memory via different techniques. No successfull execution neither.

4. I had the idea to build an .DLL file from the python code to embed this in for example a C# file 

Greetings

**Comment by alxchk** [comment]
O_O

I'm not sure I understand you. Pupy is a python interpreter (either system one or embedded to the client). So.. Well.. It just executes python code. If you ask how imports are handled - all that stuff is at pupyimporter. It's in the main module (because required at early bootstrap stages) - https://github.com/alxchk/pupy/blob/unstable/pupy/pupy/__init__.py#L503 https://github.com/alxchk/pupy/blob/unstable/pupy/pupy/__init__.py#L404

**Comment by S3cur3Th1sSh1t** [comment]
Hmm 🤔 
Let me try to put the question another way.

From my current understanding it’s not possible to execute python code on a Windows Client without python installed or without shipping an interpreter for the code, which pyinstaller for example does when compiling python code to an executable. 

So when I connect a client to pupy which doesn’t have python installed the python modules are loaded into memory of the client and executed by the client side interpreter which is embedded in the initial agent?

Im currently searching for a way to execute python code in memory of a Windows client without touching the disk and this is obviously what pupy does.

Maybe it’s easier to discuss on another channel than the github issue comments because.

**Comment by alxchk** [comment]
In case you are not using pure python client (likely you are not, because on windows it works quite bad), you already have full python environment in pupy process. Actually, all communication code is written in python, so there is no way to have connection to the pupysh wihtout some python running :) If you are using native client, you don't need to have installed python at the target. More than that, even if python installed, the host python should will not be used. I.e. the only case when host python is used - if you are using pure python target. Native client here means wrapper around python.dll.

By default client has only minimal subset of standard python library to reduce size. All other dependencies will be loaded after connection by pupysh from prebuilt bunldes.

**Comment by S3cur3Th1sSh1t** [comment]
I just found the relevant code for me which is in the client directory. python27.dll is included for the pupy client. 
So in general it should be possible to embed for example Lazagne  plus the needed imports in the client Code instead of the C2 pupysh stuff. The resulting binary should be reflectively loadable. 

This solves my questions for the moment I’ll test that the next days. 👌

**Comment by alxchk** [comment]
Weeeeeel.. Yes. It is possible. But your application will be really huge :)

**Comment by S3cur3Th1sSh1t** [comment]
Any other idea how to reflectively load python scripts?

I did compile Lazagne with nuitka to cpython, this was an 26MB executable. But this binary was not reflectively loadable, don’t know why.

The same size should be reached in memory when pupy loads Lazagne.

**Comment by alxchk** [comment]
Reflective load is a wrong term in this context. If you mean - pack everything (python + lazagne + deps) and load just from memory from single PE object - you can do this using some parts of the pupy repo. But you will need to make modifications. You need to increase payload space in the client, replace significant part of pupy/pupy (that one which about communication) with your code, and carefully find dependencies

**Comment by S3cur3Th1sSh1t** [comment]
Isn’t reflective loading the term for loading an executable and it’s dependencies to memory and execute it from there? 

This would be the next step after packing python +Lazagne + deps in an c compiled executable. 

Sounds like it’s not that easy to use pupy code as a template here. But I’ll take a look at it. Learning by doing. :P
